name: Matrix Commit Pattern

on:
  schedule:
    - cron: '20 20 * * *'  # Executa às 20:20 UTC todos os dias

jobs:
  make-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "jcpaduatimoteo09@gmail.com"  # Insira seu e-mail do GitHub
          git config --global user.name "j0a0cesar"  # Insira seu nome de usuário do GitHub

      - name: Make commits
        run: |
          # Faz 2 commits por dia
          for i in {1..2}; do
            echo "$RANDOM" > file.txt
            git add file.txt
            git commit -m "Matrix Commit $i"
          done
          git push

